[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "skiftiTools"
authors = [{name = "Hilyatushalihah Audah", email = "hkauda@utu.fi"}]
dynamic = ["version", "description"]
